# Generated by Django 4.0.2 on 2022-05-31 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptions', '0002_reception_reception_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reception',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='reception',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
