# Generated by Django 4.0.2 on 2022-05-31 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('receptions', '0003_reception_updated_at_alter_reception_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reception',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='reception',
            name='updated_at',
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('reception', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receptions.reception')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
