# Generated by Django 4.0.2 on 2022-06-04 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receptions', '0007_ingredient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reception',
            name='ingredient',
        ),
    ]
