# Generated by Django 4.0.2 on 2022-06-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptions', '0008_remove_reception_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='ingredient',
            field=models.ManyToManyField(to='receptions.Reception'),
        ),
    ]
