# Generated by Django 4.0.2 on 2022-06-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptions', '0010_rename_name_ingredient_nameing'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='ip',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
